#!/bin/sh
lock() {
    SCREEN_RESOLUTION=$(xrandr | xrandr | grep -E -o '\w*\+0\+0' | cut -d '+' -f1) 
    convert ~/Pictures/wallpaper.jpg -resize $SCREEN_RESOLUTION /tmp/crypto.png
    i3lock -f -i /tmp/crypto.png
}
 
case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac
 
exit 0
